# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../UI/EditWordDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1028, 752)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.part_of_speech_textEdit = QtWidgets.QTextEdit(self.groupBox_2)
        self.part_of_speech_textEdit.setObjectName("part_of_speech_textEdit")
        self.verticalLayout_2.addWidget(self.part_of_speech_textEdit)
        self.gridLayout.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.meaning_textEdit = QtWidgets.QTextEdit(self.groupBox_3)
        self.meaning_textEdit.setObjectName("meaning_textEdit")
        self.verticalLayout_3.addWidget(self.meaning_textEdit)
        self.gridLayout.addWidget(self.groupBox_3, 2, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.example_textEdit = QtWidgets.QTextEdit(self.groupBox_4)
        self.example_textEdit.setObjectName("example_textEdit")
        self.verticalLayout.addWidget(self.example_textEdit)
        self.gridLayout.addWidget(self.groupBox_4, 1, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.word_label = QtWidgets.QLabel(self.groupBox)
        self.word_label.setObjectName("word_label")
        self.verticalLayout_4.addWidget(self.word_label)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 2)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 3, 0, 1, 2)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setObjectName("widget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox_5 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.phonetic_symbol_textEdit = QtWidgets.QTextEdit(self.groupBox_5)
        self.phonetic_symbol_textEdit.setObjectName("phonetic_symbol_textEdit")
        self.verticalLayout_5.addWidget(self.phonetic_symbol_textEdit)
        self.verticalLayout_7.addWidget(self.groupBox_5)
        self.groupBox_6 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.audio_link_lineEdit = QtWidgets.QLineEdit(self.groupBox_6)
        self.audio_link_lineEdit.setObjectName("audio_link_lineEdit")
        self.verticalLayout_6.addWidget(self.audio_link_lineEdit)
        self.verticalLayout_7.addWidget(self.groupBox_6)
        self.gridLayout.addWidget(self.widget, 2, 1, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "编辑单词数据"))
        self.groupBox_2.setTitle(_translate("Dialog", "词性"))
        self.groupBox_3.setTitle(_translate("Dialog", "释义"))
        self.groupBox_4.setTitle(_translate("Dialog", "例句"))
        self.groupBox.setTitle(_translate("Dialog", "单词"))
        self.word_label.setText(_translate("Dialog", "TextLabel"))
        self.groupBox_5.setTitle(_translate("Dialog", "音标"))
        self.groupBox_6.setTitle(_translate("Dialog", "音频链接"))
