# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../UI/RightWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(866, 600)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.word_label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.word_label.setFont(font)
        self.word_label.setObjectName("word_label")
        self.verticalLayout_4.addWidget(self.word_label)
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color:rgb(0, 255, 0);color:rgb(255, 255, 255)")
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.play_pushButton = QtWidgets.QPushButton(Dialog)
        self.play_pushButton.setAutoDefault(False)
        self.play_pushButton.setObjectName("play_pushButton")
        self.horizontalLayout_3.addWidget(self.play_pushButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.part_label = QtWidgets.QTextBrowser(self.groupBox_3)
        self.part_label.setObjectName("part_label")
        self.verticalLayout_3.addWidget(self.part_label)
        self.verticalLayout_4.addWidget(self.groupBox_3)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.meaning_label = QtWidgets.QTextBrowser(self.groupBox_2)
        self.meaning_label.setObjectName("meaning_label")
        self.verticalLayout.addWidget(self.meaning_label)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.example_label = QtWidgets.QTextBrowser(self.groupBox)
        self.example_label.setObjectName("example_label")
        self.verticalLayout_2.addWidget(self.example_label)
        self.verticalLayout_4.addWidget(self.groupBox)
        spacerItem1 = QtWidgets.QSpacerItem(17, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.wrong_pushButton = QtWidgets.QPushButton(Dialog)
        self.wrong_pushButton.setAutoDefault(False)
        self.wrong_pushButton.setObjectName("wrong_pushButton")
        self.horizontalLayout.addWidget(self.wrong_pushButton)
        self.right_pushButton = QtWidgets.QPushButton(Dialog)
        self.right_pushButton.setAutoDefault(False)
        self.right_pushButton.setObjectName("right_pushButton")
        self.horizontalLayout.addWidget(self.right_pushButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "确认单词"))
        self.word_label.setText(_translate("Dialog", "单词"))
        self.label.setText(_translate("Dialog", "Correct"))
        self.play_pushButton.setText(_translate("Dialog", "播放音频"))
        self.groupBox_3.setTitle(_translate("Dialog", "词性"))
        self.part_label.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.groupBox_2.setTitle(_translate("Dialog", "释义"))
        self.groupBox.setTitle(_translate("Dialog", "举例"))
        self.wrong_pushButton.setText(_translate("Dialog", "记错了"))
        self.right_pushButton.setText(_translate("Dialog", "确定"))
