# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../UI/StudySpellWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(674, 436)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.word_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.word_label.setFont(font)
        self.word_label.setText("")
        self.word_label.setAlignment(QtCore.Qt.AlignCenter)
        self.word_label.setObjectName("word_label")
        self.verticalLayout.addWidget(self.word_label)
        self.play_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.play_pushButton.setObjectName("play_pushButton")
        self.verticalLayout.addWidget(self.play_pushButton)
        spacerItem = QtWidgets.QSpacerItem(20, 213, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.test_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.test_lineEdit.setFont(font)
        self.test_lineEdit.setObjectName("test_lineEdit")
        self.horizontalLayout_2.addWidget(self.test_lineEdit)
        self.ensure_pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ensure_pushButton.sizePolicy().hasHeightForWidth())
        self.ensure_pushButton.setSizePolicy(sizePolicy)
        self.ensure_pushButton.setMinimumSize(QtCore.QSize(0, 50))
        self.ensure_pushButton.setObjectName("ensure_pushButton")
        self.horizontalLayout_2.addWidget(self.ensure_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "记拼写"))
        self.play_pushButton.setText(_translate("MainWindow", "播放音频"))
        self.test_lineEdit.setPlaceholderText(_translate("MainWindow", "请输入单词"))
        self.ensure_pushButton.setText(_translate("MainWindow", "确认"))
